import { NextResponse } from 'next/server'

// GET all users
export async function GET() {
    try {
        // In a real app, you would fetch from your database
        const users = [
            { id: 1, name: 'John Doe', email: 'john@example.com' },
            { id: 2, name: 'Jane Smith', email: 'jane@example.com' }
        ]
        return NextResponse.json(users)
    } catch (error) {
        return NextResponse.json(
            { error: 'Failed to fetch users' },
            { status: 500 }
        )
    }
}

// CREATE user
export async function POST(request: Request) {
    try {
        const body = await request.json()
        // In a real app, you would save to your database
        const newUser = {
            id: 3, // This would be generated by your database
            ...body
        }
        return NextResponse.json(newUser, { status: 201 })
    } catch (error) {
        return NextResponse.json(
            { error: 'Failed to create user' },
            { status: 500 }
        )
    }
} 